# Generated by Django 5.1.7 on 2025-03-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_message_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
